-- AlterTable
ALTER TABLE "customers" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "mobileNumber" DROP DEFAULT;

-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "orderDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "orderDate" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3);
